config/routes.rb
Rails.application.routes.draw do
  # read
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  # Create
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks, only: [:title, :details]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
  @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to task_path(task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    # strong params
    params.require(:task).permit(:title, :details, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1> Add new task </h1>

app/views/tasks/edit.html.erb
<h1>Update a your task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>


  <ul>
  <% @tasks.each do |task| %>
  <li>
    <%= link_to task.title, task_path(task) %>
    <%= link_to "🗑", task_path(task), method: :delete  %>

    <% if task.complete == true %>
  <button type="button"> ✓ </button>

     <%#= evil_icon 'ei-arrow-right', size: :m %>
    <% else %>
  <button type="button" onclick="alert('Done')"> ⍻ </button>
     <%#= evil_icon 'ei-arrow-right', size: :m %>
    <% end %>
  </li>
  <% end %>
  </ul>



   <%= link_to '+ Add new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Make a new task</h1>

<!-- <form action="/tasks" method="post">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title: </label>
  <input type="text" name="tasks[tittle]" id="title">

  <label for="details">Details: </label>
  <input type="text" name="tasks[details]" id="details">

  <label for="complete">Complete: </label>
  <input type="boolean" name="tasks[complete]" id="complete">

  <input type="submit">
</form> -->

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>
<p><%= @task.complete %></p>



<%= link_to "Back", tasks_path  %>


<%= link_to 'Edit', edit_task_path %>